intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libcrails%lib{crails}

lib{crails-cookies}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+  "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-cookies}:
{
  cxx.export.poptions = "-I$out_root/libcrails-cookies/" "-I$src_root/libcrails-cookies/"
  cxx.export.libs = $intf_libs
}

liba{crails-cookies}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-cookies}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-cookies}: bin.lib.version = "-$version.project_id"
else
  lib{crails-cookies}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
